### ISSUE TITLE
no localization is implemented

### ISSUE THREAD

**Issue by caspirt** [KatsuragiG/Test4ForSmartFrameWork#2]
https://www.screenpresso.com/=UjKfe

**Comment by VladislavHodosov** [comment]
![image](https://user-images.githubusercontent.com/78086257/143539731-76accc8a-251e-4559-beb0-5105a72c9e8e.png)
Localization was implemented in App config as part of URL. I don't know, why it's not work/ on my enviroment this realization is worked.
